### ISSUE TITLE
Add new AnyNumber datatype

### ISSUE THREAD

**Issue by FelixMZ2018** [ospin-web-dev/FCTGraph#175]
Controllers should be accepting floats and integers (and cast them internally), to do this without using the any type (which we cant because then a user might connect a boolean) we need a new datatype. 

I propose `anyNumber` which can be connected to floats and ints. Firmware will have to cast it internally to whatever format they desire

**Comment by vdiezel** [comment]
@FelixMZ2018 maybe just `number` is sufficient.
